services:
  - type: web
    name: foc_simplex
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    python:
      version: 3.9.13